CREATE TABLE beers_alt_registered_user (email VARCHAR(256) NOT NULL PRIMARY KEY, username VARCHAR(256) NOT NULL);
INSERT INTO beers_alt_registered_user VALUES('vada.berkich@example.com', 'vada berkich');
INSERT INTO Registered_User VALUES('kathey.kinseth@example.com', 'kathey kinseth');
INSERT INTO Registered_User VALUES('jeff.fawcett@example.com', 'jeff fawcett');
INSERT INTO Registered_User VALUES('curt.singo@example.com', 'curt singo');
INSERT INTO Registered_User VALUES('leslie.mackinlay@example.com', 'leslie mackinlay');
INSERT INTO Registered_User VALUES('signe.feagin@example.com', 'signe feagin');
INSERT INTO Registered_User VALUES('kelsie.szerszen@example.com', 'kelsie szerszen');
INSERT INTO Registered_User VALUES('delmer.galler@example.com', 'delmer galler');
INSERT INTO Registered_User VALUES('adrien.luellen@example.com', 'adrien luellen');
INSERT INTO Registered_User VALUES('roselle.hubschmitt@example.com', 'roselle hubschmitt');
INSERT INTO Registered_User VALUES('paula.hamlin@example.com', 'paula hamlin');
INSERT INTO Registered_User VALUES('david.mulder@example.com', 'david mulder');
INSERT INTO Registered_User VALUES('adam.rovella@example.com', 'adam rovella');
INSERT INTO Registered_User VALUES('forest.elderidge@example.com', 'forest elderidge');
INSERT INTO Registered_User VALUES('gracia.melgar@example.com', 'gracia melgar');
INSERT INTO Registered_User VALUES('dean.boxley@example.com', 'dean boxley');
