CREATE TABLE Registered_User (email VARCHAR(256) NOT NULL PRIMARY KEY, username VARCHAR(256) NOT NULL);
INSERT INTO Registered_User VALUES('vada.berkich@example.com', 'vada berkich');
INSERT INTO Registered_User VALUES('kathey.kinseth@example.com', 'kathey kinseth');
INSERT INTO Registered_User VALUES('jeff.fawcett@example.com', 'jeff fawcett');
INSERT INTO Registered_User VALUES('curt.singo@example.com', 'curt singo');
INSERT INTO Registered_User VALUES('leslie.mackinlay@example.com', 'leslie mackinlay');
INSERT INTO Registered_User VALUES('signe.feagin@example.com', 'signe feagin');
INSERT INTO Registered_User VALUES('kelsie.szerszen@example.com', 'kelsie szerszen');
INSERT INTO Registered_User VALUES('delmer.galler@example.com', 'delmer galler');
INSERT INTO Registered_User VALUES('adrien.luellen@example.com', 'adrien luellen');
